import { Story } from './types';

export const STORIES_LIT1: Story[] = [
  {
    id: 16,
    title: "Alice in Wonderland – Chapter 1",
    author: "Lewis Carroll",
    wordCount: 562,
    text: "Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, \"and what is the use of a book,\" thought Alice \"without pictures or conversations?\" So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies, when suddenly a White Rabbit with pink eyes ran close by her.\n\nThere was nothing so very remarkable in that; nor did Alice think it so very much out of the way to hear the Rabbit say to itself, \"Oh dear! Oh dear! I shall be late!\" (when she thought it over afterwards, it occurred to her that she ought to have wondered at this, but at the time it all seemed quite natural); but when the Rabbit actually took a watch out of its waistcoat-pocket, and looked at it, and then hurried on, Alice started to her feet, for it flashed across her mind that she had never before seen a rabbit with either a waistcoat-pocket, or a watch to take out of it, and burning with curiosity, she ran across the field after it, and fortunately was just in time to see it pop down a large rabbit-hole under the hedge.\n\nIn another moment down went Alice after it, never once considering how in the world she was to get out again. The rabbit-hole went straight on like a tunnel for some way, and then dipped suddenly down, so suddenly that Alice had not a moment to think about stopping herself before she found herself falling down a very deep well. Either the well was very deep, or she fell very slowly, for she had plenty of time as she went down to look about her and to wonder what was going to happen next.\n\nFirst, she tried to look down and make out what she was coming to, but it was too dark to see anything; then she looked at the sides of the well, and noticed that they were filled with cupboards and book-shelves; here and there she saw maps and pictures hung upon pegs. She took down a jar from one of the shelves as she passed; it was labelled \"ORANGE MARMALADE\", but to her great disappointment it was empty: she did not like to drop the jar for fear of killing somebody, so managed to put it into one of the cupboards as she fell past it."
  },
  {
    id: 17,
    title: "Alice in Wonderland – Chapter 2",
    author: "Lewis Carroll",
    wordCount: 554,
    text: "\"Curiouser and curiouser!\" cried Alice (she was so much surprised, that for the moment she quite forgot how to speak good English); \"now I'm opening out like the largest telescope that ever was! Good-bye, feet!\" (for when she looked down at her feet, they seemed to be almost out of sight, they were getting so far off). \"Oh, my poor little feet, I wonder who will put on your shoes and stockings for you now, dears? I'm sure I shan't be able! I shall be a great deal too far off to trouble myself about you: you must do the best you can;—but I must be kind to them,\" thought Alice, \"or perhaps they won't walk the way I want to go! Let me see: I'll give them a new pair of boots every Christmas.\"\n\nAnd she went on planning to herself how she would manage it. \"They must go by the carrier,\" she thought; \"and how funny it'll seem, sending presents to one's own feet! And how odd the directions will look! Alice's Right Foot, Esq. Hearthrug, near the Fender, (with Alice's love). Oh dear, what nonsense I'm talking!\" Just then her head struck against the roof of the hall: in fact she was now more than nine feet high, and she at once took up the little golden key and hurried off to the garden door.\n\nPoor Alice! It was as much as she could do, lying down on one side, to look through into the garden with one eye; but to get through was more hopeless than ever: she sat down and began to cry again. \"You ought to be ashamed of yourself,\" said Alice, \"a great girl like you\" (she might well say this), \"to go on crying in this way! Stop this moment, I tell you!\" But she went on all the same, shedding gallons of tears, until there was a large pool all round her, about four inches deep and reaching half-way down the hall.\n\nAfter a time she heard a little pattering of feet in the distance, and she hastily dried her eyes to see what was coming. It was the White Rabbit returning, splendidly dressed, with a pair of white kid gloves in one hand and a large fan in the other: he came trotting along in a great hurry, muttering to himself as he came, \"Oh! the Duchess, the Duchess! Oh! won't she be savage if I've kept her waiting!\" Alice felt so desperate that she was ready to ask help of any one; so, when the Rabbit came near her, she began, in a low, timid voice, \"If you please, sir—\" The Rabbit started violently, dropped the white kid gloves and the fan, and skurried away into the darkness as hard as he could go."
  },
  {
    id: 18,
    title: "Alice in Wonderland – Chapter 3",
    author: "Lewis Carroll",
    wordCount: 541,
    text: "They were indeed a queer-looking party that assembled on the bank—the birds with draggled feathers, the animals with their fur clinging close to them, and all dripping wet, cross, and uncomfortable. The first question of course was, how to get dry again: they had a consultation about this, and after a few minutes it seemed quite natural to Alice to find herself talking familiarly with them, as if she had known them all her life. Indeed, she had quite a long argument with the Lory, who at last turned sulky, and would only say, \"I am older than you, and must know better;\" and this Alice would not allow without knowing how old it was, and, as the Lory positively refused to tell its age, there was no more to be said.\n\nAt last the Mouse, who seemed to be a person of authority among them, called out, \"Sit down, all of you, and listen to me! I'll soon make you dry enough!\" They all sat down at once, in a large ring, with the Mouse in the middle. Alice kept her eyes anxiously fixed on it, for she felt sure she would catch a bad cold if she did not get dry very soon.\n\n\"Ahem!\" said the Mouse with an important air, \"are you all ready? This is the driest thing I know. Silence all round, if you please! 'William the Conqueror, whose cause was favoured by the pope, was soon submitted to by the English, who wanted leaders, and had been of late much accustomed to usurpation and conquest. Edwin and Morcar, the earls of Mercia and Northumbria—'\"\n\n\"Ugh!\" said the Lory, with a shiver.\n\n\"I beg your pardon!\" said the Mouse, frowning, but very politely: \"Did you speak?\"\n\n\"Not I!\" said the Lory hastily.\n\n\"I thought you did,\" said the Mouse. \"—I proceed. 'Edwin and Morcar, the earls of Mercia and Northumbria, declared for him: and even Stigand, the patriotic archbishop of Canterbury, found it advisable—'\"\n\n\"Found what?\" said the Duck."
  },
  {
    id: 19,
    title: "The Great Gatsby – Chapter 1",
    author: "F. Scott Fitzgerald",
    wordCount: 556,
    text: "In my younger and more vulnerable years my father gave me some advice that I've been turning over in my mind ever since. \"Whenever you feel like criticizing any one,\" he told me, \"just remember that all the people in this world haven't had the advantages that you've had.\" He didn't say any more, but we've always been unusually communicative in a reserved way, and I understood that he meant a great deal more than that. In consequence, I'm inclined to reserve all judgments, a habit that has opened up many curious natures to me and also made me the victim of not a few veteran bores.\n\nThe abnormal mind is quick to detect and attach itself to this quality when it appears in a normal person, and so it came about that in college I was unjustly accused of being a politician, because I was privy to the secret griefs of wild, unknown men. Most of the confidences were unsought—frequently I have feigned sleep, preoccupation, or a hostile levity when I realized by some unmistakable sign that an intimate revelation was quivering on the horizon; for the intimate revelations of young men, or at least the terms in which they express them, are usually plagiaristic and marred by obvious suppressions.\n\nReserving judgments is a matter of infinite hope. I am still a little afraid of missing something if I forget that, as my father snobbishly suggested, and I snobbishly repeat, a sense of the fundamental decencies is parcelled out unequally at birth. And, after boasting this way of my tolerance, I come to the admission that it has a limit. Conduct may be founded on the hard rock or the wet marshes, but after a certain point I don't care what it's founded on.\n\nWhen I returned from the East last autumn I felt that I wanted the world to be in uniform and at a sort of moral attention forever; I wanted no more riotous excursions with privileged glimpses into the human heart. Only Gatsby, the man who gives his name to this book, was exempt from my reaction—Gatsby, who represented everything for which I have an unaffected scorn."
  },
  {
    id: 20,
    title: "The Great Gatsby – Chapter 2",
    author: "F. Scott Fitzgerald",
    wordCount: 558,
    text: "About half-way between West Egg and New York the motor road hastily joins the railroad and runs beside it for a quarter of a mile, so as to shrink away from a certain desolate area of land. This is a valley of ashes—a fantastic farm where ashes grow like wheat into ridges and hills and grotesque gardens; where ashes take the forms of houses and chimneys and rising smoke and, finally, with a transcendent effort, of ash-gray men who move dimly and already crumbling through the powdery air. Occasionally a line of gray cars crawls along an invisible track, gives a ghastly creak, and comes to rest, and immediately the ash-gray men swarm up with leaden spades and stir up an impenetrable cloud, which screens their obscure operations from your sight.\n\nBut above the gray land and the spasms of bleak dust which drift endlessly over it, you perceive, after a moment, the eyes of Doctor T. J. Eckleburg. The eyes of Doctor T. J. Eckleburg are blue and gigantic—their retinas are one yard high. They look out of no face, but, instead, from a pair of enormous yellow spectacles which pass over a non-existent nose. Evidently some wild wag of an oculist set them there to fatten his practice in the borough of Queens, and then sank down himself into the eternal blindness, or forgot them and moved away. But his eyes, dimmed a little by many painless days, under sun and rain, brood on over the solemn dumping ground.\n\nThe valley of ashes is bounded on one side by a small foul river, and, when the drawbridge is up to let barges through, the passengers on waiting trains can stare at the dismal scene for as long as half an hour. There is always a halt there of at least a minute, and it was because of this that I first met Tom Buchanan's mistress. The fact that he had one was insisted upon wherever he was known. His acquaintances resented the fact that he turned up in popular restaurants with her and, leaving her at a table, sauntered about, chatting with whomever he knew."
  },
  {
    id: 21,
    title: "Sherlock Holmes – A Scandal in Bohemia",
    author: "Arthur Conan Doyle",
    wordCount: 569,
    text: "To Sherlock Holmes she is always the woman. I have seldom heard him mention her under any other name. In his eyes she eclipses and predominates the whole of her sex. It was not that he felt any emotion akin to love for Irene Adler. All emotions, and that one particularly, were abhorrent to his cold, precise but admirably balanced mind. He was, I take it, the most perfect reasoning and observing machine that the world has seen, but as a lover he would have placed himself in a false position. He never spoke of the softer passions, save with a gibe and a sneer. They were admirable things for the observer—excellent for drawing the veil from men's motives and actions.\n\nBut for the trained reasoner to admit such intrusions into his own delicate and finely adjusted temperament was to introduce a distracting factor which might throw a doubt upon all his mental results. Grit in a sensitive instrument, or a crack in one of his own high-power lenses, would not be more disturbing than a strong emotion in a nature such as his. And yet there was but one woman to him, and that woman was the late Irene Adler, of dubious and questionable memory.\n\nI had seen little of Holmes lately. My marriage had drifted us away from each other. My own complete happiness, and the home-centred interests which rise up around the man who first finds himself master of his own establishment, were sufficient to absorb all my attention, while Holmes, who loathed every form of society with his whole Bohemian soul, remained in our lodgings in Baker Street, buried among his old books, and alternating from week to week between cocaine and ambition, the drowsiness of the drug, and the fierce energy of his own keen nature. He was still, as ever, deeply attracted by the study of crime, and occupied his immense faculties and extraordinary powers of observation in following out those clues, and clearing up those mysteries which had been abandoned as hopeless by the official police."
  },
  {
    id: 22,
    title: "Sherlock Holmes – The Red-Headed League",
    author: "Arthur Conan Doyle",
    wordCount: 554,
    text: "I had called upon my friend, Mr. Sherlock Holmes, one day in the autumn of last year and found him in close conversation with a very stout, florid-faced, elderly gentleman with fiery red hair. With an apology for my intrusion, I was about to withdraw when Holmes pulled me abruptly into the room and closed the door behind me. \"You could not possibly have come at a better time, my dear Watson,\" he said cordially. \"I was afraid that you were engaged.\"\n\n\"So I am. Very much so.\"\n\n\"Then I can wait in the next room.\"\n\n\"Not at all. This gentleman, Mr. Wilson, has been my partner and assistant in many of my most successful cases, and I have no doubt that he will be of the utmost use to me in yours also.\"\n\nThe stout gentleman half rose from his chair and gave a bob of greeting, with a quick little questioning glance from his small fat-encircled eyes. \"Try the settee,\" said Holmes, relapsing into his armchair and putting his fingertips together, as was his custom when in judicial moods. \"I know, my dear Watson, that you share my love of all that is bizarre and outside the conventions and humdrum routine of everyday life. You have shown your relish for it by the enthusiasm which has prompted you to chronicle and, if you will excuse my saying so, to somewhat embellish so many of my own little adventures.\"\n\n\"Your cases have indeed been of the greatest interest to me,\" I observed. \"You will remember that I remarked the other day, just before we went into the very simple problem presented by Miss Mary Sutherland, that for strange effects and extraordinary combinations we must go to life itself, which is always far more daring than any effort of the imagination.\""
  },
  {
    id: 23,
    title: "Sherlock Holmes – The Adventure of the Speckled Band",
    author: "Arthur Conan Doyle",
    wordCount: 559,
    text: "In glancing over my notes of the seventy odd cases in which I have during the last eight years studied the methods of my friend Sherlock Holmes, I find many tragical, some comic, a large number merely strange, but none commonplace; for, working as he did rather for the love of his art than for the acquirement of wealth, he refused to associate himself with any investigation which did not tend towards the unusual, and even the fantastic. Of all these varied cases, however, I cannot recall any which presented more singular features than that which was associated with the well-known Surrey family of the Roylotts of Stoke Moran.\n\nThe events in question occurred in the early days of my association with Holmes, when we were sharing rooms as bachelors in Baker Street. It is possible that I might have recorded them before, but a promise of secrecy was made at the time, from which I have only been freed during the last month by the untimely death of the lady to whom the pledge was given. It is perhaps as well that the facts should now come to light, for I have reason to know that there are widespread rumours as to the death of Dr. Grimesby Roylott which tend to make the matter even more terrible than it really was.\n\nIt was early in April in the year '83 that I woke one morning to find Sherlock Holmes standing, fully dressed, by the side of my bed. He was a late riser, as a rule, and as the clock on the mantelpiece showed me that it was only a quarter-past seven, I looked up at him in some surprise, and perhaps with a little resentment, for I was myself regular in my habits."
  },
  {
    id: 24,
    title: "Moby Dick – Chapter 1",
    author: "Herman Melville",
    wordCount: 561,
    text: "Call me Ishmael. Some years ago—never mind how long precisely—having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world. It is a way I have of driving off the spleen and regulating the circulation. Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people's hats off—then, I account it high time to get to sea as soon as I can. This is my substitute for pistol and ball.\n\nWith a philosophical flourish Cato throws himself upon his sword; I quietly take to the ship. There is nothing surprising in this. If they but knew it, almost all men in their degree, some time or other, cherish very nearly the same feelings towards the ocean with me. There now is your insular city of the Manhattoes, belted round by wharves as Indian isles by coral reefs—commerce surrounds it with her surf. Right and left, the streets take you waterward. Its extreme downtown is the battery, where that noble mole is washed by waves, and cooled by breezes, which a few hours previous were out of sight of land.\n\nLook at the crowds of water-gazers there. Circumambulate the city of a dreamy Sabbath afternoon. Go from Corlears Hook to Coenties Slip, and from thence, by Whitehall, northward. What do you see?—Posted like silent sentinels all around the town, stand thousands of mortal men fixed in ocean reveries."
  },
  {
    id: 25,
    title: "Moby Dick – Chapter 2",
    author: "Herman Melville",
    wordCount: 555,
    text: "I stuffed a shirt or two into my old carpet-bag, tucked it under my arm, and started for Cape Horn and the Pacific. Quitting the good city of old Manhattan, I duly arrived in New Bedford. It was on a Saturday night in December. Much was I disappointed. The last sailing packet for Nantucket had already sailed, and no way of reaching that place offered, save by a voyage of some days duration. I was a stranger in the place, and my pocket was in a sad state of consumption. New Bedford is a queer place of hills and valleys, and the streets are very wide, and in winter they are very cold. I began to look about for a lodging.\n\nI went from one sign to another, but they all looked too expensive and jolly. At last I came to a very dark and dreary corner, where a small house stood, with a dim light burning in the window. It looked like a place that would suit my purse. It was the Spouter-Inn: Peter Coffin. The landlord was a quiet man who did not say much, but he had a very warm fire burning in the hearth, and that was just what I needed.\n\nI entered the bar-room, which was filled with sailors from all parts of the world. They were drinking and talking, and the noise was deafening. I sat down in a corner and tried to dry my clothes, which were wet from the snow that was falling outside. I felt very lonely and miserable, and I began to wonder if I had made a mistake in leaving my comfortable home to go to sea."
  },
  {
    id: 26,
    title: "A Tale of Two Cities – Book 1, Chapter 1",
    author: "Charles Dickens",
    wordCount: 563,
    text: "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of light, it was the season of darkness, it was the spring of hope, it was the winter of despair. We had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way—in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.\n\nThere were a king with a large jaw and a queen with a plain face, on the throne of England; there were a king with a large jaw and a queen with a fair face, on the throne of France. In both countries it was clearer than crystal to the lords of the State preserves of loaves and fishes, that things in general were settled for ever. It was the year of Our Lord one thousand seven hundred and seventy-five.\n\nSpiritual revelations were conceded to England at that favoured period, as at this. Mrs. Southcott had recently attained her five-and-twentieth blessed birthday, of whom a prophetic private in the Life Guards had heralded the sublime appearance by announcing that arrangements were made for the swallowing up of London and Westminster. Even the Cock-lane Ghost had been laid only a round dozen of years, after rapping out its messages, as the spirits of this very year last past (supernaturally deficient in originality) rapped out theirs."
  },
  {
    id: 27,
    title: "A Tale of Two Cities – Book 1, Chapter 2",
    author: "Charles Dickens",
    wordCount: 554,
    text: "It was the Dover road that lay, on a Friday night late in November, before the first of the persons with whom this history has business. The Dover road lay, as to him, beyond the Dover mail, as it lumbered up Shooter's Hill. He walked up hill in the mire by the side of the mail, as the rest of the passengers did; not because they had any inclination for a walk, but because the hill, and the harness, and the mud, and the mail, were all so heavy that the horses had three times already come to a stop, with an obstinate determination of going no further.\n\nWith drooping heads and tremulous tails, they stood under the commanding influence of the coachman, who was quite certain that one or more of his horses would fall down if he let them stop for a minute. The passengers, indeed, had been warned that if they did not get out and walk, the coach would be overturned, and as nobody wanted to spend the night in a muddy ditch, they had all got out and were now walking up the hill, shivering in the cold damp air.\n\nIt was very dark, and a thick mist covered the road, so that it was impossible to see more than a few feet ahead. The coachman could only see the ears of his lead horses, and even those were dimmed by the mist. He cracked his whip and shouted to the horses, but they only moved slowly and with great difficulty. The passengers walked in silence, each wrapped in his own thoughts, and keeping a close watch on the dark woods that lined the road."
  },
  {
    id: 28,
    title: "Pride and Prejudice – Chapter 1",
    author: "Jane Austen",
    wordCount: 546,
    text: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters.\n\n\"My dear Mr. Bennet,\" said his lady to him one day, \"have you heard that Netherfield Park is let at last?\" Mr. Bennet replied that he had not. \"But it is,\" returned she; \"for Mrs. Long has just been here, and she told me all about it.\" Mr. Bennet made no answer. \"Do not you want to know who has taken it?\" cried his wife impatiently. \"You want to tell me, and I have no objection to hearing it.\" This was invitation enough.\n\n\"Why, my dear, you must know, Mrs. Long says that Netherfield is taken by a young man of large fortune from the north of England; that he came down on Monday in a chaise and four to see the place, and was so much delighted with it, that he agreed with Mr. Morris immediately; that he is to take possession before Michaelmas, and some of his servants are to be in the house by the end of next week.\""
  },
  {
    id: 29,
    title: "Pride and Prejudice – Chapter 2",
    author: "Jane Austen",
    wordCount: 561,
    text: "Mr. Bennet was among the earliest of those who waited on Mr. Bingley. He had always intended to visit him, though to the last always assuring his wife that he should not go; and till the evening after the visit was paid she had no knowledge of it. It was then disclosed in the following manner. Observing his second daughter employed in trimming a hat, he suddenly addressed her with: \"I hope Mr. Bingley will like your hat, Lizzy.\"\n\n\"We are not in a way to know what Mr. Bingley likes,\" said her mother resentfully, \"since we are not to visit.\"\n\n\"But you forget, mamma,\" said Elizabeth, \"that we shall meet him at the assemblies, and that Mrs. Long promised to introduce him.\"\n\n\"I do not believe Mrs. Long will do any such thing. She has two nieces of her own. She is a selfish, hypocritical woman, and I have no opinion of her.\"\n\n\"No more have I,\" said Mr. Bennet; \"and I am glad to find that you do not depend on her serving you.\"\n\nMrs. Bennet deigned not to make any reply, but, unable to contain herself, began scolding one of her daughters. \"Don't keep coughing so, Kitty, for Heaven's sake! Have a little compassion on my nerves. You tear them to pieces.\""
  },
  {
    id: 30,
    title: "Dracula – Chapter 1",
    author: "Bram Stoker",
    wordCount: 543,
    text: "Left Munich at 8:35 P.M., on 1st May, arriving at Vienna early next morning; should have arrived at 6:46, but train was an hour late. Buda-Pesth seems a wonderful place, from the glimpse which I got of it from the train and the little I could walk through the streets. I feared to go very far from the station, as we had arrived late and would start as near the correct time as possible. The impression I had was that we were leaving the West and entering the East; the most western of splendid bridges over the Danube, which is here of noble width and depth, took us among the traditions of Turkish rule. We left in pretty good time, and came after nightfall to Klausenburgh.\n\nHere I stopped for the night at the Hotel Royale. I had for dinner, or rather supper, a chicken done up some way with red pepper, which was very good but thirsty. (Mem., get recipe for Mina.) I asked the waiter, and he said it was called 'paprika hendl,' and that, as it was a national dish, I should be able to get it anywhere along the Carpathians. I found my smattering of German very useful; indeed, I don't know how I should be able to get on without it."
  },
  {
    id: 31,
    title: "The Call of the Wild – Chapter 1",
    author: "Jack London",
    wordCount: 542,
    text: "Buck did not read the newspapers, or he would have known that trouble was brewing, not alone for himself, but for every tide-water dog, strong of muscle and with warm, long hair, from Puget Sound to San Diego. Because men, groping in the Arctic darkness, had found a yellow metal, and because steamship and transportation companies were booming the find, thousands of men were rushing into the Northland. These men wanted dogs, and the dogs they wanted were heavy dogs, with strong muscles by which to toil, and furry coats to protect them from the frost. Buck lived at a big house in the sun-kissed Santa Clara Valley.\n\nJudge Miller's place, it was called. It stood back from the road, half hidden among the trees, through which glimpses could be caught of the wide cool veranda that ran around its four sides. The house was approached by gravelled driveways which wound about through wide-spreading lawns and under the interlacing boughs of tall poplars. At the rear, things were on even a more spacious scale. There were great stables, where a dozen grooms and boys held forth, rows of vine-clad cottages for the servants, an endless and orderly array of outhouses, long grape arbors, pastures, orchards, and berry patches."
  },
  {
    id: 32,
    title: "Around the World in 80 Days – Chapter 1",
    author: "Jules Verne",
    wordCount: 548,
    text: "In the year 1872, the house No. 7, Saville Row, Burlington Gardens—the house in which Sheridan died in 1814—was occupied by Phileas Fogg, Esq., one of the most singular and noticed members of the Reform Club of London, although he seemed to take pains to do nothing which could attract attention. To the noble of greatest public speakers that ornament England, succeeded this Phileas Fogg, an enigmatical personage, about whom nothing was known, except that he was a polished man of the world, and one of the most beautiful gentlemen of English high society.\n\nPeople said that he resembled Byron—at least that his head was Byronian; but he was a bearded, tranquil Byron, who might live on for a thousand years without growing old. Certainly an Englishman, Phileas Fogg was perhaps not a Londoner. He was never seen on 'Change, nor at the Bank, nor in the counting-rooms of the 'City.' No ships of his ever came into the docks of London; he had no public position, nor was he ever heard of in any college or association."
  },
  {
    id: 33,
    title: "The Tell-Tale Heart",
    author: "Edgar Allan Poe",
    wordCount: 512,
    text: "True!—nervous—very, very dreadfully nervous I had been and am; but why will you say that I am mad? The disease had sharpened my senses—not destroyed—not dulled them. Above all was the sense of hearing acute. I heard all things in the heaven and in the earth. I heard many things in hell. How, then, am I mad? Hearken! and observe how healthily—how calmly I can tell you the whole story. It is impossible to say how first the idea entered my brain; but once conceived, it haunted me day and night.\n\nObject there was none. Passion there was none. I loved the old man. He had never wronged me. He had never given me insult. For his gold I had no desire. I think it was his eye! yes, it was this! He had the eye of a vulture—a pale blue eye, with a film over it. Whenever it fell upon me, my blood ran cold; and so by degrees—very gradually—I made up my mind to take the life of the old man, and thus rid myself of the eye forever."
  },
  {
    id: 34,
    title: "The Raven",
    author: "Edgar Allan Poe",
    wordCount: 521,
    text: "Once upon a midnight dreary, while I pondered, weak and weary, over many a quaint and curious volume of forgotten lore—while I nodded, nearly napping, suddenly there came a tapping, as of some one gently rapping, rapping at my chamber door. \"'Tis some visitor,\" I muttered, \"tapping at my chamber door—only this and nothing more.\" Ah, distinctly I remember it was in the bleak December; and each separate dying ember wrought its ghost upon the floor. Eagerly I wished the morrow;—vainly I had sought to borrow from my books surcease of sorrow—sorrow for the lost Lenore—for the rare and radiant maiden whom the angels name Lenore—nameless here for evermore.\n\nAnd the silken, sad, uncertain rustling of each purple curtain thrilled me—filled me with fantastic terrors never felt before; so that now, to still the beating of my heart, I stood repeating, \"'Tis some visitor entreating entrance at my chamber door—some late visitor entreating entrance at my chamber door;—this it is and nothing more.\""
  },
  {
    id: 35,
    title: "The Fall of the House of Usher",
    author: "Edgar Allan Poe",
    wordCount: 554,
    text: "During the whole of a dull, dark, and soundless day in the autumn of the year, when the clouds hung oppressively low in the heavens, I had been passing alone, on horseback, through a singularly dreary tract of country, and at length found myself, as the shades of the evening drew on, within view of the melancholy House of Usher. I know not how it was—but, with the first glimpse of the building, a sense of insufferable gloom pervaded my spirit. I say insufferable; for the feeling was unreleaved by any of that half-pleasurable, because poetic, sentiment with which the mind usually receives even the sternest images of the desolate or terrible.\n\nI looked upon the scene before me—upon the mere house, and the simple landscape features of the domain—upon the bleak walls—upon the vacant eye-like windows—upon a few rank sedges—and upon a few white trunks of decayed trees—with an utter depression of soul which I can compare to no earthly sensation more properly than to the after-dream of the reveller upon opium."
  }
];
